### ISSUE TITLE
Использование com.google.android.gms

### ISSUE THREAD

**Issue by AlexeyMeshkov** [odnoklassniki/ok-android-sdk#2]
Класс OkDevice использует Google API для получения рекламного идентификатора устройства. При этом SDK сам по себе не использует  эту функциональность. Предполагается, что этим кодом воспользуется пользователь для передачи результата в sdk.getInstallSource.

Таким образом пользователи SDK вынуждены подключать в своё приложение библиотеки Google-сервисов, даже если они на самом деле не нужны. В нашем случае приложение написано на Adobe AIR и OK SDK завёрнуто в расширение. Подключить туда гуглосервисы возможно, но крайне неудобно. А получить рекламный идентификатор мы можем и сами.

Имхо этот код нужно просто убрать из SDK и поместить его в примеры.

**Comment by lintax** [comment]
Мне кажется более правильным решением для конкретного сценария было бы посмотреть в сторону conditional dependencies (или просто +1 модуль), и вынести код работы с gcm в подмодуль, чье подключение или нет может контролировать клиент.

**Comment by lintax** [comment]
Бтв каким образом без gcm AIR может получать advertising id?

**Comment by AlexeyMeshkov** [comment]
Код получения advertising id в Android - тривиален и найти его и использовать не составляет труда. При этом этот код в OK SDK сам по себе не нужен - нужны только результаты его работы, а здесь GCM - лишняя зависимость.

Не может конечно. Но для этого у нас уже есть отдельное расширение и advertising id у нас уже есть.

**Comment by AlexeyMeshkov** [comment]
А вообще возможно стоит посмотреть, как это сделано в Facebook SDK. Они сами внутри получают рекламный идентификатор, но при этом не требуют явных зависимостей от GCM. У них для этого есть класс [GoogleAdInfo](https://github.com/facebook/facebook-android-sdk/blob/b0012b5a66b76433ad59abcce54ee5114e5df6cb/facebook/src/main/java/com/facebook/internal/AttributionIdentifiers.java#L278).

**Comment by lintax** [comment]
Fixed https://github.com/odnoklassniki/ok-android-sdk/commit/93d2ed064f42f9949a8c88c584c47f69829220d5
