### ISSUE TITLE
Authorization activity doesn't finish if account gets changed via Google

### ISSUE THREAD

**Issue by lidaamber** [odnoklassniki/ok-android-sdk#21]
Steps to reproduce:

1. Call `requestAuthorization()` method to open OkAuthActivity
2. Click `change account` to open login screen
3. Click `forgot my password`
4. Click `Sign in with Google`
5. Sign in successfully
6. See the OK feed screen, not initial activity. Clicking back button leads to cancelling authorization or retrying it.

Same for the first sign in via Google. I don't have OK application on the test phone (maybe it matters).

**Comment by lintax** [comment]
Thanks, its a bug in OK application, not SDK. Passed it to the app core team.

**Comment by lintax** [comment]
Please update the SDK. We will retry OAUTH in such scenario, this should work perfectly with no extra screens, etc.
