### ISSUE TITLE
On Error возвращает пустую строку

### ISSUE THREAD

**Issue by chim0380** [odnoklassniki/ok-android-sdk#25]
Версия SDK 2.1.5
При авторизации при помощи SDK в событие OnError иногда  возвращается пустая строка, вместо описания ошибки

onActivityResult  в родительском Activity  был вызван c параметрами:
 **requestCode**=22890, **resultCode**=2

Ошибка была замечена на 19 и 23 версиях Api Android 

Если это штатная ситуация , что можно сообщить пользователю в данном случае?

**Comment by lintax** [comment]
Это не совсем штатная ситуация и при типичной авторизации такого результата не должно быть.
Я бы наверно выводил ошибку по умолчанию при отсутствии ошибки, вроде "Ошибка авторизации".
Возможно, этот generic вид ошибки можно зашить и в sdk..
