### ISSUE TITLE
Документация на сайте

### ISSUE THREAD

**Issue by sergpalm** [odnoklassniki/ok-android-sdk#27]
В руководстве читаю, что 
odnoklassniki.request(METHOD_NAME, params, "GET");

Делаю - вижу Deprecated

Как правильно делать запрос odnoklassniki.request - где можно увидеть пример

**Comment by lintax** [comment]
Да, https://apiok.ru/en/dev/sdk/android -- там ещё и версия очень старая - этого метода давно нет

Лучше посмотреть на примере, который внутри самого sdk в репозитории лежит - https://github.com/odnoklassniki/ok-android-sdk/blob/master/odnoklassniki-android-sdk-example/src/main/java/ru/ok/android/sdk/example/MainActivity.kt
Доку - запишем и обновим

**Comment by sergpalm** [comment]
В указанной ссылке нет примера с request - мой вопрос как правильно делать request

**Comment by lintax** [comment]
есть, например [MainActivity.kt#L44](https://github.com/odnoklassniki/ok-android-sdk/blob/master/odnoklassniki-android-sdk-example/src/main/java/ru/ok/android/sdk/example/MainActivity.kt#L44)

request / requestAsync концептуально не отличаются
