### ISSUE TITLE
OkTokenRequestListener 

### ISSUE THREAD

**Issue by hram** [odnoklassniki/ok-android-sdk#3]
В документации на SDK сказано "Для обработки авторизации необходимо, чтобы активити реализовало интерфейс OkTokenRequestListener (методы onSuccess, onCancel и onError)"

В SDK не нашел OkTokenRequestListener

**Comment by lintax** [comment]
Можно посмотреть пример, приложенный в https://github.com/odnoklassniki/ok-android-sdk/tree/master/odnoklassniki-android-sdk-example
А документация на apiok - да, несколько устарела

**Comment by thefilin** [comment]
Действительно, в новой версии SDK нет onCancel.
Есть предложение, как разделить неудачные кейсы OAuth между onError и onCancel ?

Например, сейчас, если отказаться выдавать пермиссии приложению, происходит редирект с параметром error, также, если есть проблема в настройках (запрашивается response_type=token, а у приложения не включен клиентский OAuth), то приходит редирект с тем же error, но другим текстом.

**Comment by lintax** [comment]
А чем должны различаться обработки ошибки и отмена?
Суть с точки зрения API схожа - приложению отказано в доступе под текущим пользователем (причем та же отмена может быть на первом окне, а может при применении пермиссий) - или же спам система, например, отменила возможность заходить этим пользователем или в это приложение.
Какой практический смысл различать эти состояния? Как мне кажется, потребность в такой настройке низка, и может быть достигнута обработкой определенной ошибки.

**Comment by hram** [comment]
@lintax как обработать ошибку чтобы узнать отмену?

**Comment by lintax** [comment]
Просьба предоставить конкретный естественный пример, когда типичной игре/приложению надо различать события - ошибка и отменил пользователь.

**Comment by hram** [comment]
Пример есть. Конкретный. Предоставить не могу. Требования заказчика. Отмена и ошибка это разные сценарии. С этим думаю сложно спорить. В документации написано что их можно различать. Заказчик захотел их различать.

**Comment by lintax** [comment]
Если сценария нет - есть обходное решение - посмотреть как называется ошибка, которая возвращается в случае отмены и проверять на то вернулась ли она или нет

**Comment by hram** [comment]
Пустой спор какой то. Это разные действия. Ошибка авторизации и отмена авторизации. Заказчик хочет их различать и это его право.
А подвязываться на текст сообщения об ошибке это как?
Действительно думаете что это норма?
А если вы текст поменяете?
А если текст ошибки на разных языках будет отличаться?
Странно такое слышать от одноклассников.

**Comment by hram** [comment]
@thefilin прошу о помощи

**Comment by lintax** [comment]
Такой функциональности нет и не планируется. Если будет естественный
сценарий необходимости то можно рассматривать расширения API в рамках
развития oauth.
