### ISSUE TITLE
Nullable аргумент обладает NonNull типом

### ISSUE THREAD

**Issue by CodeBreak524** [odnoklassniki/ok-android-sdk#31]
Версия 2.1.8.
В методе `Odnoklassniki.requestAuthorization` есть аргумент `@Nullable redirectUri: String`. Он помечен аннотацией, однако сам тип не является nullable, т.к. он не `String?`. В связи с этим при использовании этого метода на котлине невозможно прокинуть null в качестве аргумента.

**Comment by lintax** [comment]
Да, осталось после автоконвертации)
Исправлю, но версию пока не буду релизить
как временное решение можно заполнять fallback url-ом "okauth://auth", но рекомендуется id приложения вставлять, как в примере
