### ISSUE TITLE
Ошибка постинга в ОК при определенной структуре доменного имени

### ISSUE THREAD

**Issue by goonerpi** [odnoklassniki/ok-android-sdk#32]
При попытке постинга в одноклассники не открывается окно для подтверждения постинга. Если делать то же самое в тестовом приложении Одноклассников, подставив туда свои данные, выдается тост с ошибкой:
_errors.web-grabber.communication-error._
Как оказалось, ошибка возникает из-за типа моей ссылки, на которую перенаправляется юзер после клика на пост (поле _link_ в OK SDK). А именно, если в доменном имени присутствует несколько точек (напр. _www.test.site.com_, _www.login.my.site.com_).

**Comment by lintax** [comment]
Скорее всего проблема не в точках, а в тегах страницы или какой-то подобной проблемы.
Можете указать используемый домен/страницу, чтобы можно было в логах граббера посмотреть?

**Comment by goonerpi** [comment]
А может ли проблема быть связана с тем, что сайт использует http-авторизацию прямо при заходе на сайт? Делалось, чтобы не индексировался в поиске

**Comment by lintax** [comment]
Может) Чтобы ссылка обработалась, она должна быть доступна для граббинга
