### ISSUE TITLE
Не вызывается onCancel по отмене авторизации

### ISSUE THREAD

**Issue by jgnt32** [odnoklassniki/ok-android-sdk#34]
Не вызывается `onCancel` по отмене авторизации при установленном, но не авторизованном приложении Одноклассники. Ошибка 100% в самом приложении, не SDK. Пинганите их там.

**Comment by lintax** [comment]
Ок, посмотрим. Если проблема есть - запланируем починку

**Comment by lintax** [comment]
должно будет исправится вскоре с обновлением клиента OK
