### ISSUE TITLE
Сделать requestAuthorization принимающий Fragment а не Activity

### ISSUE THREAD

**Issue by gorelov-a** [odnoklassniki/ok-android-sdk#35]
Сделать аналогичный метод 
`requestAuthorization(fragment: Fragment, authType: OkAuthType, vararg scopes: String)`
 и что бы startActivityForResult вызывался на Fragment`e

**Comment by lintax** [comment]
Это поможет только на top-level фрагменте. Если он будет nested, то это ничего не даст, если вы сами не броадкастите по всем фрагментам onActivityResult.
Почему вы не хотите обработать ответ в активности?

**Comment by gorelov-a** [comment]
Удобно логику разбивать по фрагментам. Наша архитектура устроена таким образом, что удобно SDK запускать из Fragment'а и обрабатывать результат тоже во Fragment'e. Nested Fregment`ы довольно редко используются, а вот top-level обычная практика с подходом Single Activity.
