### ISSUE TITLE
Участились IP_BLOCKED : REST access denied for not listed IP

### ISSUE THREAD

**Issue by chim0380** [odnoklassniki/ok-android-sdk#37]
Версия SDK 2.1.8

Время от времени у пользователей возникают ошибки:

> IP_BLOCKED : REST access denied for not listed IP xxx.xxx.xxx.xxx (check app server ip configuration)

Причем, пару раз это было и на эмуляторе  на машине разработчика, который явно имеет добропорядочный ip.

Проверьте, все ли **ok**  у **OK** в этом вопросе.

**Comment by lintax** [comment]
ошибка означает, что вы вызваете подписанный секретным ключём приложения метод с непрописанного адреса

**Comment by chim0380** [comment]
К сожалению, не понятен Ваш ответ.
 С какого не прописанного адреса и где его нужно прописать?
Ошибки продолжают поступать, с разных  IP.

**Comment by lintax** [comment]
вы вызываете с клиента метод, который предназначен для вызова с вашего сервера, с прописанного в профиле ip адреса

**Comment by chim0380** [comment]
На клиенте мы вызываем только  те методы вашего android sdk , которые необходимы для авторизации. Точно по документации. Со своего сервера ничего не вызываем. У вас в документации нет ничего про сервер при авторизации при помощи  android sdk.

 Ошибки пользователей продолжаются:

**IP_BLOCKED : REST access denied for not listed IP 5.140.XX.XXX (check app server ip configuration)** 

Устройство  Galaxy S10 не рутованно.
Дата сбоя: 30 июн. 2020 г., 00:11:00 по Москве

**Comment by lintax** [comment]
Какие методы вы вызываете?

Ещё раз, если метод подписывается секретным ключём приложения, он должен вызываться с сервера а не с клиента, и ip адреса/маски сервера должны быть прописаны в профиле приложения.

**Comment by chim0380** [comment]
Обращаемся из своего приложения andriod согласно  инструкции  https://apiok.ru/dev/sdk/android
 
создание/получение экземпляра Odnoklassniki
odnoklassniki = Odnoklassniki.createInstance(this, "APP_ID", OK_APP_PUBLIC_KEY_INDEX);
 
Вызов авторизации (requestAuthorization)
odnoklassniki.requestAuthorization(this,REDIRECT_URI, OkAuthType.ANY, OkScope.VALUABLE_ACCESS);
        
Запрос информации о пользователе
HashMap<String, String> params = new HashMap<>();
params.put("fields", OK_SCOPE);
odnoklassniki.requestAsync("users.getCurrentUser", params, OkRequestMode.getDEFAULT(), new OkListener() {}
 
Больше ничего не вызываем.
Если нужно что-то вызывать с сервера, пришлите пожалуйста ссылку, где об этом упоминается.

**Comment by chim0380** [comment]
Описанные выше ошибки продолжаются
