### ISSUE TITLE
Не устанавливается приложение на Android 5 с подключенным OK SDK

### ISSUE THREAD

**Issue by popov-sa** [odnoklassniki/ok-android-sdk#38]
Собственно САБЖ.  

После подключения OK Android SDK пользователи с **Android 5** начали испытывать трудности при скачивании и установке приложения из Google Play.  
Приложение вовсе не запускается, и выдает ошибку еще на этапе установки приложения.

Поскольку ошибка возникает еще на этапе установки, не приходит никаких отчетов о сбоях.

Чтобы выявить ошибку, собрали несколько тестовых сборок, и на устройствах Android 5 не устанавливается именно сборка с OK Android SDK.  
Очевидно, что ошибка где-то в OK Android SDK.

Версия SDK 2.1.8

**Comment by lintax** [comment]
Ошибка при установке обычно означает, что пакет не совместим с устройством, например:
- собран под другой процессор
- имеет более высокий minSdkVersion
- уже установлено приложение с не меньшим кодом версии
и другие

Для начала я бы проверил эту гипотезу

**Comment by popov-sa** [comment]
Еще раз по порядку:  
Сделали 2 тестовые сборки.  
Они полностью идентичны, за исключением того, что в одной подключен OK Android SDK, в другой - нет.  
Сборка без OK Android SDK устанавливается без проблем.  
Сборка с OK Android SDK не устанавливается на Android 5.

> собран под другой процессор  

Как я уже сказал, сборки идентичны. Отличаются только наличием OK Android SDK.  

> имеет более высокий minSdkVersion  

minSdkVersion одинаковая в обеих сборках, и совпадает с minSdkVersion в OK Android SDK - 16.

> уже установлено приложение с не меньшим кодом версии  

Приложение ставится не поверх существующей версии.   
Сперва удаляется старая версия, потом ставится новая.

**Comment by lintax** [comment]
ну смотрите, я поднял эмулятор с api 21 (5.0). собрал пример. задеплоил.
поставилось и работает.
у вас пример из sdk запускается на 5м андроиде?

**Comment by popov-sa** [comment]
Да у нас дело в том, что на своих устройствах с Android 5 воспроизвести ошибку так и не удалось((  

Мы просили внешнего тестировщика, у которого эта проблема проявилась, проверить на своем устройстве, и он сказал, что проблема возникает именно со сборкой, где присутствует OK SDK.

После Вашего ответа мы попросили этого тестировщика еще раз все перепроверить, и после перепроверки выяснилось, что повторно не устанавливаются и другие альтернативные сборки...((

Баг ведет себя непредсказуемо, и ошибка, судя по всему, не в OK SDK, а все таки где-то в другом месте... В общем, будем дальше копаться у себя.

Спасибо Вам за быстрый ответ и потраченное время)
Тему закрываю
