### ISSUE TITLE
Not-null assertion в Odnoklassniki.request()

### ISSUE THREAD

**Issue by sntgl** [odnoklassniki/ok-android-sdk#43]
Сейчас в методе `request` класса `Odnoklassniki` используется not-null assertion для поля `mAccessToken`.

У нас происходили гонки состояний, поэтому приложение могло падать на этом assert'e (порядка 150 падений в день).

Предлагается сделать этот вызов безопасным:

```
        mAccessToken?.let { accessToken ->
            if (mode.contains(OkRequestMode.SIGNED)) {
                signParameters(requestParams)
                requestParams[PARAM_ACCESS_TOKEN] = accessToken
            }
        }
```

**Comment by lintax** [comment]
PR вмержен
