### ISSUE TITLE
Error: Отменено

### ISSUE THREAD

**Issue by wdkcjnwdwkldn** [odnoklassniki/ok-android-sdk#6]
При попытке авторизоваться через установленный клиент после ввода логина и пароля возвращается ошибка с текстом "Отменено".
Если повторить запрос авторизации - открывается окно, на котором подтверждается вход.
Через WebView авторизация с вводом логина и пароля проходит без ошибок.

**Comment by lintax** [comment]
Да, в случае, когда в приложении OK пользователь не залогинен, первая авторизация через SSO OAUTH не проходит

**Comment by lintax** [comment]
Ошибка не в SDK а самом приложении OK, уехало в другой трекер
