### ISSUE TITLE
performPosting

### ISSUE THREAD

**Issue by UsovSam** [odnoklassniki/ok-android-sdk#8]
При попытки вызвать виджет постинга получаю ошибку Parameter 'PHOTO id' is invalid, иногда появляется ошибка BAD id. В чем может быть проблема?
До этого получаю ссылку для загрузки сервера, загружаю картинку и получаю id и token картинки.
После этого создаю attachment
"{" +
                        "\"media\":[" +
                        "{" +
                        "\"type\":\"text\"," +
                        "\"text\":\"hello world!\"" +
                        "},{" +
                        "\"type\":\"photo\"," +
                        "\"list\":[" +
                        "{" + "\"id\":\"" + token + "\"" + "}," +
                        "{" + "\"photoId\":\"" + id + "\"" + "}" +
                        "]" +
                        "}" +
                        "]" +
                        "}";
Подскажите , пожалуйста, где у меня ошибка...

**Comment by strlght** [comment]
Я правильно понимаю, что в приложенном json'е публикуется одна фотка? Если да, то советую прочитать раздел "Элементы media" в https://apiok.ru/wiki/display/api/mediatopic.post+ru

Если вкратце, то:
- для одной фотки нужно передавать либо id, либо photoId,
- есть ряд ограничений на фотографии.

**Comment by UsovSam** [comment]
Спасибо! Надо указывать лишь один id.. я неправильно разобрал пример в документации.
