### ISSUE TITLE
Не получается вернуться обратно в приложение после отмены в авторизации через клиента

### ISSUE THREAD

**Issue by ssergo** [odnoklassniki/ok-android-sdk#9]
В случае успешной авторизации я возвращаюсь в предыдущее активити, в случае отмены (backButton) - выкидывает домой, и мне приходится заходить в мое свернутое приложение. Есть идеи, как вернуться в активити?

**Comment by UsovSam** [comment]
а у меня вообще не открывается активити для разрешения. Но при этом, если выйти из приложения и заново зайти, то токен получен и можно работать дальше. При вызове метода requestAuthorization сразу вызывается метод OnActivityResult с ошибкой {"activity_result":0}. Как это пофиксить?

**Comment by ssergo** [comment]
@1SemmeS1, запускаешь приложенный к сдк пример? Убери android:launchMode="singleTask" у OkAuthActivity в манифесте. [http://stackoverflow.com/questions/8960072/onactivityresult-with-launchmode-singletask](url)

**Comment by UsovSam** [comment]
@ssergo, спасибо за ответ! Все получилось! Да, запускал с примера.. Но вот с возвратом такая же беда.. Если найду решение, то обязательно поделюсь..

**Comment by lintax** [comment]
Если что, пулл реквесты принимаются

**Comment by lintax** [comment]
Не получается повторить сценарий - при отмене возвращается в example приложение
